[project]
name = "pychess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ttkbootstrap>=1.13.8",
]
